[pytest]
testpaths = tests
markers =
    api: API tests
    ui: UI tests
    auth: Authentication tests
    integration: Integration tests
addopts = -ra -q --html=reports/report.html --self-contained-html
